# Generated by Django 4.1.7 on 2023-03-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category_product_lux_product_lux1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lux',
            new_name='luxury_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='lux1',
            new_name='luxury_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lux2',
        ),
    ]
