# Generated by Django 4.1.7 on 2023-03-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website_Shop',
        ),
    ]
